### ISSUE TITLE
Einrichtung Lightgallery

### ISSUE THREAD

**Issue by bkrmb** [heimseiten/contao-lightgallery-js-bundle#1]
Ich möchte gerne die lightgallery für Youtube Videos nutzen. Im Seitenlayout ist js-lightgallery aktiviert und der Code wird auch im Quelltext angezeigt. 
Wie kann ich die lightgallery ansteuern? Mit "data- lightgallery"?

**Comment by heimseiten** [comment]
Tigger ist a[target="lightbox"]. Habe die README.md aktualisiert.
